diffusion_config:
  num_timesteps: 1000
  beta_init: 0.0001
  beta_end: 0.02
  num_inference_steps: 100
  indexes_range : 16
  eta: 0.0
  sigma_y: 0.1
  guidance_scale: 0.1
  sampler: ddim_pseudo_guidance
  save: true
  mode: super_res

model_config:
  im_channels: 3
  im_size: 256

train_config:
  image_index: 100
  num_grid_rows: 1

number_images: 16

csv_path: "samples/results"
